### ISSUE TITLE
Old SSL-Fingerprints in PyPi version

### ISSUE THREAD

**Issue by datamaan** [figo-connect/python-figo#4]
Hi,

could you please update the PyPi package of python-figo? It still contains the old ssl fingerprints and thus does not work.

Thanks!

**Comment by JDHH83** [comment]
Quick Fix: Add fingerprint 38:AE:4A:32:6F:16:EA:15:81:33:8B:B0:D8:E4:A6:35:E7:27:F1:07 to your local figo.py file. On linux under /usr/local/lib/pythonX.X/dist-packages/figo/

**Comment by fricklerhandwerk** [comment]
This is fixed as of version 1.5.8.
